-- MySQL Script generated by MySQL Workbench
-- 12/15/14 16:36:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema findaldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema findaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `findaldb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `findaldb` ;

-- -----------------------------------------------------
-- Table `findaldb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findaldb`.`users` (
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` INT NULL,
  `PERMISSIONS` INT(1) NULL,
  `L_NAME` VARCHAR(45) NULL,
  `F_NAME` VARCHAR(45) NULL,
  `PERMISSIONS` INT NULL,
  `CRN` INT(9) NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findaldb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findaldb`.`courses` (
  `NAME` VARCHAR(45) NULL,
  `ID` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `TEACHER_EMAIL` VARCHAR(45) NULL,
  `CRN` INT(9) NOT NULL,
  PRIMARY KEY (`CRN`),
  INDEX `fk_courses_users1_idx` (`TEACHER_EMAIL` ASC),
  CONSTRAINT `fk_courses_users1`
    FOREIGN KEY (`TEACHER_EMAIL`)
    REFERENCES `findaldb`.`users` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `findaldb`.`enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `findaldb`.`enrollment` (
  `CRN` INT(9) NULL,
  `EMAIL` VARCHAR(45) NULL,
  INDEX `fk_students_courses1_idx` (`CRN` ASC),
  INDEX `fk_students_users1_idx` (`EMAIL` ASC),
  CONSTRAINT `fk_students_courses1`
    FOREIGN KEY (`CRN`)
    REFERENCES `findaldb`.`courses` (`CRN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_users1`
    FOREIGN KEY (`EMAIL`)
    REFERENCES `findaldb`.`users` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
