# Simple makefile
# not spaces.
# Note: lines that start with a pound symbol are comments

#Compile source code by typing the command make compile
compile:
	javac *.java
#Run the P5_detective java main class by typing the command make run
run:
	java P5_Detective dictionary.data moo oom

#Clean the class files
clean:
	rm *.class
