

<!-- this is the page seen by users playing the game -->




<!-- Auto generated by eclilpse -->
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>

<!-- auto generated by eclipse -->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

<head>

<!-- auto generated by eclipse -->
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">

<title>Bunco Simulation!</title>

</head>



<body>


	<h1>Bunco!</h1>

	<!-- Head Table -->
	<h3>Head Table</h3>

	<!-- End Head Table -->

	<!-- Table One -->
	<h3>Table One</h3>

	<!-- End Table One -->

	<!-- Table Two -->
	<h3>Table Two</h3>

	<!-- End Table Two -->


	<!-- Buttons -->
	<!-- Form to Continue Play -->
	<input type=submit value="Continue">

	<!-- Form to Exit Play -->
	<input type=submit value="Exit">
	<!-- end buttons -->

</body>

</html>