
<!-- this is the default page seen by users -->





<!-- auto-generated by eclipse -->
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>


<!-- auto generated by eclipse -->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

<head>

<!-- Link to Style.css -->
<link rel="stylesheet" type="text/css" href="Style.css">

<!-- auto generated by eclipse -->
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">

<title>Bunco!</title>

</head>

<body>

	<!-- Inform the User About Bunco -->
	<!-- Heading -->
	<h1>Bunco!</h1>

	<!-- paragraph -->
	<p>Bunco is a parlour game played in teams with three dice.</p>

	<!-- Heading -->
	<h3>Brief Program Description</h3>

	<!-- paragraph -->
	<p>
		Bunco is a dice game that is played in teams with three dice per team.
		Bunco was originally "8-Dice cloth" according to the World Bunco
		Association a dice game in 18th-century England. It was imported to
		San Francisco as a gambling activity in 1855, where it gave its name
		to gambling parlors, or Bunco parlors, and more generally to any
		swindle. After the Civil War the game evolved to a popular parlor
		game. During the 1920s and Prohibition, Bunco was re-popularized as a
		gambling game, often associated with a speakeasy. Law-enforcement
		groups raiding these parlors came to be known as "Bunco squads". Bunco
		as a family game saw a resurgence in popularity in the 1980s. (from
		wikipedia: <a href="http://en.wikipedia.org/wiki/Bunco">wikilink</a>).
	</p>

	<!-- Header -->
	<h3>Bunco Resources:</h3>

	<!-- paragraph -->
	<p>You can read about the game of Bunco at the following Web sites.
	</p>


	<!-- unordered list -->
	<ul>

		<li>Bunco Wikipedia page - <a
			href="http://en.wikipedia.org/wiki/Bunco">Wikipedia</a>
		</li>

		<li>Bunco Rules - <a href="http://www.buncogame.com/bunco-rules">Bunco
				Rules</a>
		</li>

	</ul>


	<!-- Form to Begin Play -->

	<form name='playGame' action='play' method='post'>
		<input type='hidden' name='tableOnePlayer' value='North' /> <input
			type='hidden' name='tableTwoPlayer' value='North' /> <input
			type='hidden' name='tableOneTotal' value='0' /> <input type='hidden'
			name='tableTwoTotal' value='0' /> <input type='hidden' name='round'
			value='1' /> <input type='hidden' name='roundCount' value='2' /> <input
			type='submit' value='Play Bunco!'>
	</form>



</body>

</html>