<!-- autogenerated by eclipse -->
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<!-- head -->
<head>
<link rel="stylesheet" type="text/css" href="style.css">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<%@ page import="model.Academic"%>

<title>Oasis</title>
</head>

<!-- Body -->
<body>
	<!-- retrieve table from request -->
	<%
		//get the message or table
		String m = "Welcome to Oasis, the terrible old registration system for UGA students. Now deprecated and replaced by Athena.  Check <a href='https://athena.uga.edu/'>Athena</a> out, it is so much better</p>";

		//get user's permissions to properly display panel
		int permissions = 4;
		String nav = "";
		try {
			Academic user = (Academic) request.getSession().getAttribute(
					"user");
			permissions = user.getPermissions();
		} catch (Exception e) {
			permissions = 4;
		}

		switch (permissions) {

		case 0: {
			nav += "<li>";
			nav += "<a href='student'>Student</a>";
			nav += "</li>";
			break;
		}
		case 1: {

			nav += "<li>";
			nav += "<a href='teacher'>Teacher</a>";
			nav += "</li>";
			break;
		}
		case 2: {
			nav += "<li>";
			nav += "<a href='admin'>Admin</a>";
			nav += "</li>";
			break;
		}

		}//end switch

		if (permissions < 3 && permissions >= 0) {
			nav += "<li>";
			nav += "<a href='Logout'>Sign Out</a>";
			nav += "</li>";
		}

		//get the message from the servlet. if an error occurs, no message was forwarded from server, so display defualt message
		try {

			if (request.getAttribute("msg") != null) {
				m = (String) request.getAttribute("msg");
			}
		} catch (Exception e) {
			m = "Welcome to Oasis, the terrible old registration system for UGA students. Now deprecated and replaced by Athena.  Check <a href='https://athena.uga.edu/'>Athena</a> out, it is so much better</p>";

		}
	%>


	<!-- Navigation -->
	<div class='nav'>
		<ul>
			<li><a href="index.jsp">Home</a></li>
			<li><a href="browse">Course List</a></li>
			<%=nav%>
		</ul>
	</div>
	<h1>Oasis Homepage</h1>

	<h3>Log In</h3>
	<form name="login" action="Login" method="POST">

		<input type="email" name="userName" value="Email" required> <input
			type="password" name="password" value="Password" required> <input
			type="submit" name="log in" value="Login">
	</form>

	<p><%=m%></p>





</body>
</html>