# Simple makefile
# not spaces.
# Note: lines that start with a pound symbol are comments

#Compile source code by typing the command make compile
compile:
	javac *.java
#Run the Hello java main class by typing the command make run
run:
	java Hangman Computer random
#Clean the class files
clean:
	rm Player.class
	rm Board.class
	rm Hangman.class
	rm HangmanBoard.class
	rm ComputerPlayer.class
	rm NaiveComputerPlayer.class
	rm PlayFasterComputerPlayer.class
	rm HumanPlayer.class
	rm RandomComputerPlayer.class
	rm SmartAIComputerPlayer.class
	rm CutThroatComputerPlayer.class
	rm DualPrintStream.class
#run_faster, runs our ai, which is far superior
#to doc's 
run_faster:
	java Hangman Computer Human

